### ISSUE TITLE
Add card portfolio for the rest of countries

### ISSUE THREAD

**Issue by gausoft** [ln-dev7/world-portfolios#82]
Like this image : [public/assets/images/cm/card-portfolio.png](https://github.com/ln-dev7/world-portfolios/blob/master/public/assets/images/cm/card-portfolio.png)

It would be nice to have a banner like for others countries. 
The card below is for TG, for example :

<img src="https://github.com/ln-dev7/world-portfolios/assets/26385667/5cf65436-0532-4f12-a224-4a11498ba241" width="160"/>

**Comment by ln-dev7** [comment]
<img width="1440" alt="Capture d’écran 2023-07-16 à 12 34 25" src="https://github.com/ln-dev7/world-portfolios/assets/62269693/2e6de932-472c-4033-a87e-6424627811cc">

Done :)
